insert into style (style) values ('Biografias e Memórias');
insert into style (style) values ('Contos');
insert into style (style) values ('Cordel');
insert into style (style) values ('Crônicas');
insert into style (style) values ('Ensaios');
insert into style (style) values ('Eróticos');
insert into style (style) values ('Ficção Científica');
insert into style (style) values ('Novela');
insert into style (style) values ('Poesia');
insert into style (style) values ('Policial');
insert into style (style) values ('Romance');
insert into style (style) values ('Romance Autobiografico');
insert into style (style) values ('Romance Histórico');
insert into style (style) values ('Teatro');
insert into style (style) values ('Terror');
insert into style (style) values ('Tragédia');
insert into style (style) values ('Baseado em fatos reais');
insert into style (style) values ('Livro-reportagem');
insert into style (style) values ('Quadrinhos');